import { openrouter } from "../openrouter";

export const GOOGLE_MODELS = [
  {
    id: "google/gemma-3-4b-it:free",
    name: "Gemma 3 4B",
    subName: "Free",
    provider: "openrouter",
    displayProvider: "google",
    premium: false,
    usesPremiumCredits: false,
    description:
      "Google Gemma 3 4B instruction-tuned model (free tier on OpenRouter).",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    api_sdk: openrouter("google/gemma-3-4b-it:free"),
    features: [],
  },
  {
    id: "google/gemma-3-12b-it",
    name: "Gemma 3 12B",
    provider: "openrouter",
    displayProvider: "google",
    premium: false,
    usesPremiumCredits: false,
    description: "Google Gemma 3 12B instruction-tuned model.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    api_sdk: openrouter("google/gemma-3-12b-it"),
    features: [],
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma 3 27B",
    provider: "openrouter",
    displayProvider: "google",
    premium: false,
    usesPremiumCredits: false,
    description: "Google Gemma 3 27B instruction-tuned model.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    api_sdk: openrouter("google/gemma-3-27b-it"),
    features: [],
  },
  {
    id: "google/gemma-2-9b-it",
    name: "Gemma 2 9B",
    provider: "openrouter",
    displayProvider: "google",
    premium: false,
    usesPremiumCredits: false,
    description: "Google Gemma 2 9B instruction-tuned model.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    api_sdk: openrouter("google/gemma-2-9b-it"),
    features: [],
  },
  {
    id: "google/gemma-2-27b-it",
    name: "Gemma 2 27B",
    provider: "openrouter",
    displayProvider: "google",
    premium: false,
    usesPremiumCredits: false,
    description: "Google Gemma 2 27B instruction-tuned model.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    api_sdk: openrouter("google/gemma-2-27b-it"),
    features: [],
  },
];
